import type { Locale } from "@/lib/i18n";

const copy = {
  security: [
    "Account security",
    "Seguridad de la cuenta",
    "Segurança da conta",
  ],
  currentPassword: ["Current password", "Contraseña actual", "Senha atual"],
  newPassword: [
    "New password (at least 14 characters)",
    "Nueva contraseña (al menos 14 caracteres)",
    "Nova senha (pelo menos 14 caracteres)",
  ],
  passwordChanged: [
    "Password changed. Other sessions have been signed out.",
    "Contraseña cambiada. Las otras sesiones se han cerrado.",
    "Senha alterada. As outras sessões foram encerradas.",
  ],
  password_changed: [
    "Password changed",
    "Contraseña cambiada",
    "Senha alterada",
  ],
  passwordHint: [
    "Enter your current password and a new authenticator code. Changing your password signs out all other sessions.",
    "Introduce tu contraseña actual y un código nuevo del autenticador. Cambiar la contraseña cerrará las otras sesiones.",
    "Digite sua senha atual e um novo código do autenticador. Alterar a senha encerrará as outras sessões.",
  ],
  resetAccess: [
    "Reset account enrollment",
    "Restablecer activación de cuenta",
    "Redefinir ativação da conta",
  ],
  resetAccessHint: [
    "Resetting enrollment signs out this staff member and requires a new password and authenticator setup.",
    "Restablecer la activación cerrará las sesiones de esta persona y requerirá una contraseña nueva y configurar el autenticador.",
    "Redefinir a ativação encerrará as sessões desta pessoa e exigirá uma nova senha e configuração do autenticador.",
  ],
  age_seconds: [
    "Last heartbeat (seconds)",
    "Última señal (segundos)",
    "Último sinal (segundos)",
  ],
  oldest_seconds: [
    "Oldest pending (seconds)",
    "Más antiguo pendiente (segundos)",
    "Mais antigo pendente (segundos)",
  ],
  runtime: ["Game service", "Servicio de juego", "Serviço de jogo"],
  wallet: [
    "Wallet recovery",
    "Recuperación del monedero",
    "Recuperação da carteira",
  ],
  stale: ["Heartbeat overdue", "Señal atrasada", "Sinal atrasado"],
  admin: ["Administration", "Administración", "Administração"],
  workspace: [
    "Operations workspace",
    "Espacio de operaciones",
    "Área de operações",
  ],
  overview: ["Overview", "Resumen", "Visão geral"],
  operators: ["Clients", "Clientes", "Clientes"],
  sessions: ["Sessions", "Sesiones", "Sessões"],
  transactions: ["Transactions", "Transacciones", "Transações"],
  rounds: ["Rounds", "Rondas", "Rodadas"],
  report: ["Reports", "Informes", "Relatórios"],
  operations: ["Operations", "Operaciones", "Operações"],
  audit: ["Audit trail", "Registro de auditoría", "Registro de auditoria"],
  staff: ["Team & access", "Equipo y acceso", "Equipe e acesso"],
  integration: [
    "Integration desk",
    "Centro de integración",
    "Central de integração",
  ],
  signIn: ["Sign in", "Iniciar sesión", "Entrar"],
  signOut: ["Sign out", "Cerrar sesión", "Sair"],
  username: ["Username", "Nombre de usuario", "Nome de usuário"],
  password: ["Password", "Contraseña", "Senha"],
  code: [
    "Authenticator code",
    "Código del autenticador",
    "Código do autenticador",
  ],
  loginHint: [
    "Use your staff account and the current code from your authenticator app.",
    "Usa tu cuenta de personal y el código actual de tu aplicación de autenticación.",
    "Use sua conta de equipe e o código atual do aplicativo autenticador.",
  ],
  activate: ["Activate account", "Activar cuenta", "Ativar conta"],
  inviteToken: [
    "Invitation token",
    "Código de invitación",
    "Código de convite",
  ],
  continue: ["Continue", "Continuar", "Continuar"],
  mfaTitle: [
    "Set up your authenticator",
    "Configura tu autenticador",
    "Configure seu autenticador",
  ],
  mfaHint: [
    "Add this account to an authenticator app using the setup key. Enter its six-digit code and choose a password of at least 14 characters.",
    "Añade esta cuenta a una aplicación de autenticación con la clave de configuración. Introduce su código de seis dígitos y elige una contraseña de al menos 14 caracteres.",
    "Adicione esta conta a um aplicativo autenticador usando a chave de configuração. Digite o código de seis dígitos e escolha uma senha com pelo menos 14 caracteres.",
  ],
  setupKey: ["Setup key", "Clave de configuración", "Chave de configuração"],
  openAuthenticator: [
    "Open authenticator",
    "Abrir autenticador",
    "Abrir autenticador",
  ],
  backWebsite: ["Back to website", "Volver al sitio web", "Voltar ao site"],
  language: ["Language", "Idioma", "Idioma"],
  theme: ["Theme", "Tema", "Tema"],
  system: ["System", "Sistema", "Sistema"],
  light: ["Light", "Claro", "Claro"],
  dark: ["Dark", "Oscuro", "Escuro"],
  loading: [
    "Loading your workspace…",
    "Cargando tu espacio de trabajo…",
    "Carregando sua área de trabalho…",
  ],
  refresh: ["Refresh", "Actualizar", "Atualizar"],
  updated: ["Last updated", "Última actualización", "Última atualização"],
  empty: [
    "No records match these filters.",
    "No hay registros que coincidan con estos filtros.",
    "Nenhum registro corresponde a estes filtros.",
  ],
  error: [
    "We couldn’t complete this request. Please try again.",
    "No pudimos completar la solicitud. Inténtalo de nuevo.",
    "Não foi possível concluir a solicitação. Tente novamente.",
  ],
  unavailable: [
    "The administration service is temporarily unavailable.",
    "El servicio de administración no está disponible temporalmente.",
    "O serviço de administração está temporariamente indisponível.",
  ],
  expired: [
    "Your session expired. Sign in again to continue.",
    "Tu sesión ha caducado. Inicia sesión de nuevo para continuar.",
    "Sua sessão expirou. Entre novamente para continuar.",
  ],
  forbidden: [
    "Your role does not permit this action.",
    "Tu rol no permite esta acción.",
    "Sua função não permite esta ação.",
  ],
  loginFailed: [
    "Check your username, password and a new authenticator code.",
    "Comprueba tu usuario, contraseña y un código nuevo del autenticador.",
    "Confira seu usuário, senha e um novo código do autenticador.",
  ],
  rateLimited: [
    "Too many attempts. Please wait before trying again.",
    "Demasiados intentos. Espera antes de volver a intentarlo.",
    "Muitas tentativas. Aguarde antes de tentar novamente.",
  ],
  invalidInvitation: [
    "This invitation is invalid, used or expired. Ask an owner for a new invitation.",
    "Esta invitación no es válida, ya se usó o caducó. Pide una nueva a un propietario.",
    "Este convite é inválido, já foi usado ou expirou. Peça um novo a um proprietário.",
  ],
  sandbox: [
    "Sandbox · simulated activity",
    "Sandbox · actividad simulada",
    "Sandbox · atividade simulada",
  ],
  sandboxHint: [
    "These are actual sandbox records. Demo credits have no monetary value.",
    "Estos son registros reales del sandbox. Los créditos de demostración no tienen valor monetario.",
    "Estes são registros reais do sandbox. Os créditos de demonstração não têm valor monetário.",
  ],
  activeSessions: ["Active sessions", "Sesiones activas", "Sessões ativas"],
  allSessions: ["Total sessions", "Sesiones totales", "Total de sessões"],
  pending: [
    "Pending settlement",
    "Liquidación pendiente",
    "Liquidação pendente",
  ],
  serviceHealth: ["Service health", "Estado del servicio", "Estado do serviço"],
  healthy: ["Healthy", "Correcto", "Saudável"],
  attention: ["Needs attention", "Requiere atención", "Requer atenção"],
  capacity: [
    "Session capacity",
    "Capacidad de sesiones",
    "Capacidade de sessões",
  ],
  clientCapacity: [
    "Per-client limit",
    "Límite por cliente",
    "Limite por cliente",
  ],
  maintenance: ["Maintenance", "Mantenimiento", "Manutenção"],
  paused: ["Paused", "Pausado", "Pausado"],
  running: [
    "Accepting new games",
    "Aceptando nuevos juegos",
    "Aceitando novos jogos",
  ],
  alerts: ["Alerts", "Alertas", "Alertas"],
  noAlerts: [
    "No active alerts.",
    "No hay alertas activas.",
    "Não há alertas ativos.",
  ],
  workers: [
    "Recovery services",
    "Servicios de recuperación",
    "Serviços de recuperação",
  ],
  oldest: [
    "Oldest pending (seconds)",
    "Más antiguo pendiente (segundos)",
    "Mais antigo pendente (segundos)",
  ],
  age: [
    "Last heartbeat (seconds)",
    "Última señal (segundos)",
    "Último sinal (segundos)",
  ],
  role: ["Role", "Rol", "Função"],
  status: ["Status", "Estado", "Estado"],
  game: ["Game", "Juego", "Jogo"],
  games: ["Assigned games", "Juegos asignados", "Jogos atribuídos"],
  allGames: ["All games", "Todos los juegos", "Todos os jogos"],
  allClients: ["All clients", "Todos los clientes", "Todos os clientes"],
  allStatuses: ["All statuses", "Todos los estados", "Todos os estados"],
  operator_id: ["Client", "Cliente", "Cliente"],
  name: ["Name", "Nombre", "Nome"],
  id: ["ID", "ID", "ID"],
  player_id: ["Player ID", "ID de jugador", "ID do jogador"],
  session_id: ["Session ID", "ID de sesión", "ID da sessão"],
  transaction_id: ["Transaction ID", "ID de transacción", "ID da transação"],
  round_id: ["Round ID", "ID de ronda", "ID da rodada"],
  currency: ["Currency", "Moneda", "Moeda"],
  currencies: ["Currencies", "Monedas", "Moedas"],
  origins: [
    "Approved website origins",
    "Orígenes web aprobados",
    "Origens web aprovadas",
  ],
  wallet_url: [
    "Wallet callback URL",
    "URL de callback del monedero",
    "URL de callback da carteira",
  ],
  environment: ["Environment", "Entorno", "Ambiente"],
  demo: ["Public demo", "Demo pública", "Demo pública"],
  created_at: [
    "Created (local time)",
    "Creado (hora local)",
    "Criado (hora local)",
  ],
  updated_at: [
    "Updated (local time)",
    "Actualizado (hora local)",
    "Atualizado (hora local)",
  ],
  expires_at: [
    "Expires (local time)",
    "Caduca (hora local)",
    "Expira (hora local)",
  ],
  redeemed: ["Game opened", "Juego abierto", "Jogo aberto"],
  operation: ["Operation", "Operación", "Operação"],
  amount: ["Amount", "Importe", "Valor"],
  attempts: [
    "Delivery attempts",
    "Intentos de entrega",
    "Tentativas de entrega",
  ],
  bet: ["Bet", "Apuesta", "Aposta"],
  win: ["Payout", "Pago", "Pagamento"],
  bets: ["Settled bets", "Apuestas liquidadas", "Apostas liquidadas"],
  payouts: ["Settled payouts", "Pagos liquidados", "Pagamentos liquidados"],
  ggr: ["Settled GGR", "GGR liquidado", "GGR liquidado"],
  simulated: ["Simulated", "Simulado", "Simulado"],
  filters: ["Filters", "Filtros", "Filtros"],
  search: ["Search IDs", "Buscar IDs", "Buscar IDs"],
  searchClients: ["Search clients", "Buscar clientes", "Buscar clientes"],
  start: ["From (UTC)", "Desde (UTC)", "De (UTC)"],
  end: ["To (UTC)", "Hasta (UTC)", "Até (UTC)"],
  apply: ["Apply filters", "Aplicar filtros", "Aplicar filtros"],
  reset: ["Reset filters", "Restablecer filtros", "Redefinir filtros"],
  export: ["Export CSV", "Exportar CSV", "Exportar CSV"],
  exportLimit: [
    "Narrow the filters to export up to 5,000 rows.",
    "Reduce los filtros para exportar hasta 5.000 filas.",
    "Restrinja os filtros para exportar até 5.000 linhas.",
  ],
  invalidDates: [
    "Choose a valid date range of up to one year.",
    "Elige un período válido de hasta un año.",
    "Escolha um período válido de até um ano.",
  ],
  previous: ["Previous", "Anterior", "Anterior"],
  next: ["Next", "Siguiente", "Próximo"],
  records: ["Records", "Registros", "Registros"],
  details: ["View details", "Ver detalles", "Ver detalhes"],
  close: ["Close", "Cerrar", "Fechar"],
  cancel: ["Cancel", "Cancelar", "Cancelar"],
  save: ["Save changes", "Guardar cambios", "Salvar alterações"],
  saved: ["Changes saved.", "Cambios guardados.", "Alterações salvas."],
  confirmTitle: [
    "Review and confirm",
    "Revisar y confirmar",
    "Revisar e confirmar",
  ],
  confirmId: [
    "Type the client ID to confirm",
    "Escribe el ID del cliente para confirmar",
    "Digite o ID do cliente para confirmar",
  ],
  settlementNotice: [
    "Accepted payouts and refunds continue after suspension or maintenance.",
    "Los pagos y reembolsos aceptados continúan después de suspender o activar el mantenimiento.",
    "Pagamentos e reembolsos aceitos continuam após suspensão ou manutenção.",
  ],
  manage: ["Manage client", "Gestionar cliente", "Gerenciar cliente"],
  activateClient: ["Activate client", "Activar cliente", "Ativar cliente"],
  suspendClient: ["Suspend client", "Suspender cliente", "Suspender cliente"],
  credentials: ["API credentials", "Credenciales API", "Credenciais da API"],
  issueKey: [
    "Issue a new API key",
    "Emitir nueva clave API",
    "Emitir nova chave de API",
  ],
  revoke: ["Revoke", "Revocar", "Revogar"],
  keyOnce: [
    "Copy this credential now. It will not be shown again. Store it privately in the client’s server configuration.",
    "Copia esta credencial ahora. No se mostrará de nuevo. Guárdala de forma privada en la configuración del servidor del cliente.",
    "Copie esta credencial agora. Ela não será exibida novamente. Guarde-a de forma privada na configuração do servidor do cliente.",
  ],
  copy: ["Copy", "Copiar", "Copiar"],
  copied: ["Copied", "Copiado", "Copiado"],
  keyRotation: [
    "Issue a replacement, verify the client has switched, then revoke the previous key.",
    "Emite una clave nueva, comprueba que el cliente la usa y después revoca la anterior.",
    "Emita uma nova chave, confirme que o cliente a está usando e depois revogue a anterior.",
  ],
  owner: ["Owner", "Propietario", "Proprietário"],
  manager: ["Manager", "Gestor", "Gestor"],
  viewer: ["Viewer", "Lector", "Leitor"],
  active: ["Active", "Activo", "Ativo"],
  disabled: ["Disabled", "Desactivado", "Desativado"],
  invited: ["Invited", "Invitado", "Convidado"],
  suspended: ["Suspended", "Suspendido", "Suspenso"],
  closed: ["Closed", "Cerrado", "Fechado"],
  success: ["Successful", "Correcto", "Bem-sucedido"],
  settled: ["Settled", "Liquidado", "Liquidado"],
  rejected: ["Rejected", "Rechazado", "Rejeitado"],
  cancelled: ["Cancelled", "Cancelado", "Cancelado"],
  unknown: ["Unresolved", "Sin resolver", "Não resolvido"],
  sending: ["Delivering", "Enviando", "Enviando"],
  debit_pending: ["Debit pending", "Débito pendiente", "Débito pendente"],
  debit: ["Debit", "Débito", "Débito"],
  credit: ["Credit", "Crédito", "Crédito"],
  rollback: ["Reversal", "Reversión", "Estorno"],
  balance: ["Balance check", "Consulta de saldo", "Consulta de saldo"],
  ok: ["Healthy", "Correcto", "Saudável"],
  revoked: ["Revoked", "Revocado", "Revogado"],
  reportHint: [
    "Settled bets minus settled payouts, grouped by client and currency. Dates use settlement time in UTC. This is gross gaming revenue from simulated rounds, not net profit or an invoice.",
    "Apuestas liquidadas menos pagos liquidados, agrupados por cliente y moneda. Las fechas usan la hora de liquidación en UTC. Son ingresos brutos de rondas simuladas, no beneficios netos ni una factura.",
    "Apostas liquidadas menos pagamentos liquidados, agrupados por cliente e moeda. As datas usam o horário de liquidação em UTC. É a receita bruta de rodadas simuladas, não lucro líquido nem uma fatura.",
  ],
  callbacks: [
    "Callback delivery",
    "Entrega de callbacks",
    "Entrega de callbacks",
  ],
  controlsHint: [
    "The current server supports up to four concurrent sessions and two per client. Lowering limits does not interrupt accepted settlements.",
    "El servidor actual admite hasta cuatro sesiones simultáneas y dos por cliente. Reducir los límites no interrumpe las liquidaciones aceptadas.",
    "O servidor atual suporta até quatro sessões simultâneas e duas por cliente. Reduzir os limites não interrompe liquidações aceitas.",
  ],
  pauseGames: [
    "Pause new games and wagers",
    "Pausar juegos y apuestas nuevos",
    "Pausar novos jogos e apostas",
  ],
  actor: ["Actor", "Responsable", "Responsável"],
  action: ["Action", "Acción", "Ação"],
  target: ["Target", "Destino", "Destino"],
  source: ["Source", "Origen", "Origem"],
  count: ["Count", "Cantidad", "Quantidade"],
  teamHint: [
    "Owners manage access and credentials. Managers operate clients and maintenance. Viewers can inspect records and export reports.",
    "Los propietarios gestionan accesos y credenciales. Los gestores operan clientes y mantenimiento. Los lectores consultan registros y exportan informes.",
    "Proprietários gerenciam acessos e credenciais. Gestores operam clientes e manutenção. Leitores consultam registros e exportam relatórios.",
  ],
  invite: [
    "Invite staff member",
    "Invitar miembro del equipo",
    "Convidar membro da equipe",
  ],
  inviteOnce: [
    "Share this private activation link directly with the intended staff member. It expires in 24 hours.",
    "Comparte este enlace privado de activación directamente con la persona indicada. Caduca en 24 horas.",
    "Compartilhe este link privado de ativação diretamente com a pessoa indicada. Ele expira em 24 horas.",
  ],
  changeAccess: ["Change access", "Cambiar acceso", "Alterar acesso"],
  selfChange: [
    "Another owner must change your own access.",
    "Otro propietario debe cambiar tu propio acceso.",
    "Outro proprietário deve alterar seu próprio acesso.",
  ],
  enrollmentRequired: [
    "Complete the invitation before activating this account.",
    "Completa la invitación antes de activar esta cuenta.",
    "Conclua o convite antes de ativar esta conta.",
  ],
  staffExists: [
    "This username already exists.",
    "Este nombre de usuario ya existe.",
    "Este nome de usuário já existe.",
  ],
  integrationHint: [
    "Use client-specific API credentials on your server. Public visitors use isolated demos; the former shared Client A/B lab has been retired.",
    "Usa credenciales API específicas de cada cliente en tu servidor. Los visitantes usan demos aisladas; el antiguo laboratorio compartido A/B se ha retirado.",
    "Use credenciais de API específicas de cada cliente no seu servidor. Visitantes usam demos isoladas; o antigo laboratório compartilhado A/B foi desativado.",
  ],
  docs: [
    "Developer documentation",
    "Documentación para desarrolladores",
    "Documentação para desenvolvedores",
  ],
  publicGames: [
    "Public game demos",
    "Demos públicas de juegos",
    "Demos públicas dos jogos",
  ],
  onboard: [
    "Enroll prepared client",
    "Registrar cliente preparado",
    "Cadastrar cliente preparado",
  ],
  onboardingHint: [
    "First install the client’s callback secret, approved callback host and operator ID in the server deployment. Prepared entries then become available here. New clients start suspended.",
    "Primero instala el secreto de callback, el host de callback aprobado y el ID del cliente en el despliegue del servidor. Después aparecerán aquí. Los clientes nuevos comienzan suspendidos.",
    "Primeiro instale o segredo de callback, o host de callback aprovado e o ID do cliente na implantação do servidor. Depois eles aparecerão aqui. Novos clientes começam suspensos.",
  ],
  noPrepared: [
    "No prepared clients are waiting for enrollment.",
    "No hay clientes preparados pendientes de registro.",
    "Não há clientes preparados aguardando cadastro.",
  ],
  secretRef: [
    "Installed signing-secret reference",
    "Referencia del secreto de firma instalado",
    "Referência do segredo de assinatura instalado",
  ],
  notConfigured: [
    "The client’s server configuration needs attention before activation.",
    "La configuración del servidor del cliente requiere atención antes de activarlo.",
    "A configuração do servidor do cliente precisa ser revisada antes da ativação.",
  ],
  recovery_worker_unavailable: [
    "A recovery service is unavailable",
    "Un servicio de recuperación no está disponible",
    "Um serviço de recuperação está indisponível",
  ],
  wallet_secret_missing: [
    "Client callback configuration is missing",
    "Falta configuración de callback del cliente",
    "Falta configuração de callback do cliente",
  ],
  operator_not_enrolled: [
    "A configured client is not enrolled",
    "Un cliente configurado no está registrado",
    "Um cliente configurado não está cadastrado",
  ],
  wallet_obligation_overdue: [
    "A wallet callback is overdue",
    "Un callback del monedero está atrasado",
    "Um callback da carteira está atrasado",
  ],
  round_recovery_overdue: [
    "A round needs recovery attention",
    "Una ronda necesita revisión de recuperación",
    "Uma rodada precisa de revisão de recuperação",
  ],
  login_succeeded: ["Signed in", "Inicio de sesión", "Entrada"],
  login_failed: [
    "Failed sign-in",
    "Inicio de sesión fallido",
    "Falha ao entrar",
  ],
  logout: ["Signed out", "Cierre de sesión", "Saída"],
  staff_invited: ["Staff invited", "Miembro invitado", "Membro convidado"],
  staff_enrolled: ["Staff activated", "Miembro activado", "Membro ativado"],
  staff_access_changed: [
    "Staff access changed",
    "Acceso del equipo cambiado",
    "Acesso da equipe alterado",
  ],
  staff_host_recovery: [
    "Account recovery",
    "Recuperación de cuenta",
    "Recuperação de conta",
  ],
  api_key_issued: [
    "API key issued",
    "Clave API emitida",
    "Chave de API emitida",
  ],
  api_key_revoked: [
    "API key revoked",
    "Clave API revocada",
    "Chave de API revogada",
  ],
  status_changed: [
    "Client status changed",
    "Estado del cliente cambiado",
    "Estado do cliente alterado",
  ],
  games_changed: [
    "Game assignments changed",
    "Asignación de juegos cambiada",
    "Atribuição de jogos alterada",
  ],
  enrolled: ["Client enrolled", "Cliente registrado", "Cliente cadastrado"],
  data_exported: ["Data exported", "Datos exportados", "Dados exportados"],
  deployment_changed: [
    "Deployment controls changed",
    "Controles del despliegue cambiados",
    "Controles da implantação alterados",
  ],
  yes: ["Yes", "Sí", "Sim"],
  no: ["No", "No", "Não"],
} as const;
export type AdminCopy = Record<keyof typeof copy, string>;
export function getAdminCopy(locale: Locale): AdminCopy {
  const index = { en: 0, es: 1, pt: 2 }[locale];
  return Object.fromEntries(
    Object.entries(copy).map(([key, value]) => [key, value[index]]),
  ) as AdminCopy;
}
